#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DuurHooiClicker.Resource", IsApplication=true)]

namespace DuurHooiClicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int achievement_100000clicks_disabled = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int achievement_100000clicks_enabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int achievement_10000clicks_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int achievement_10000clicks_enabled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int achievement_1000clicks_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int achievement_1000clicks_enabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int achievement_honderdduizendhooi_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int achievement_honderdduizendhooi_enabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int achievement_miljardhooi_disabled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int achievement_miljardhooi_enabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int achievement_miljoenhooi_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int achievement_miljoenhooi_enabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int hay = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int FindHay = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int HayCursus = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int HayLabel = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int btnAchievements = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int btnPassiveHay = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int btnStartGame = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int btnUpgradeHayCursus = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int file_settings = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int gridAchievements = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int tableRow1 = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int upgrade_haycursus_10 = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int upgrade_haycursus_100 = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int upgrade_haycursus_25 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int upgrade_haycursus_50 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int upgrade_haycursus_max = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int upgrade_hay_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int menutheme = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
