#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DuurHooiClicker.Resource", IsApplication=true)]

namespace DuurHooiClicker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int black = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int darkgray = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int gray = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int silver = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int achievement_100000clicks_disabled = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int achievement_100000clicks_enabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int achievement_10000clicks_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int achievement_10000clicks_enabled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int achievement_1000clicks_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int achievement_1000clicks_enabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int achievement_honderdduizendhooi_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int achievement_honderdduizendhooi_enabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int achievement_miljardhooi_disabled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int achievement_miljardhooi_enabled = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int achievement_miljoenhooi_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int achievement_miljoenhooi_enabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int hay = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_achievements = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_settings = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090003
			public const int FindHay = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int HayCursus = 2131296261;
			
			// aapt resource value: 0x7f090002
			public const int HayLabel = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int btnPassiveHay = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int btnUpgradeHayCursus = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int file_settings = 2131296266;
			
			// aapt resource value: 0x7f090001
			public const int gridAchievements = 2131296257;
			
			// aapt resource value: 0x7f090008
			public const int menu_achievements = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int menu_settings = 2131296265;
			
			// aapt resource value: 0x7f090004
			public const int tableRow1 = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int toolbar = 2131296256;
			
			// aapt resource value: 0x7f09000b
			public const int upgrade_haycursus_10 = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int upgrade_haycursus_100 = 2131296270;
			
			// aapt resource value: 0x7f09000c
			public const int upgrade_haycursus_25 = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int upgrade_haycursus_50 = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int upgrade_haycursus_max = 2131296271;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Achievements = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int toolbar = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int top_menus = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int upgrade_hay_menu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int menutheme = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
